### ISSUE TITLE
Scrolling / Long data loading performance

### ISSUE THREAD

**Issue by PiMaV** [PiMaV/BLITZ#66]
When having big data matrix, scrolling to timeline cant be stopped and leads to freeze or restart.
Maybe this could help:

https://www.geeksforgeeks.org/prevent-freezing-in-python-pyqt-guis-with-qthread/

Connected to #37 . Which could be merged or closed once this is done

**Comment by irkri** [comment]
Everything in Blitz depends on the image shown. Therefore, in order to use any option or transformation, an ongoing operation has to be finished before another can begin.
For example, I have to stop scrolling so that an image is loaded. I can then do someting with this image afterwards.

Threads are used when something should be running in the background. We use threads right now in the web connection to WOLKE and the camera handling in the live view. 

I don't see how we can use threads to speed up scrolling or dragging ROI. Additionally, all of this is implemented by pyqtgraph, so we would have to implement everything on our own as far as I can tell.

**Comment by PiMaV** [comment]
Closed for now. Currently we dont have time for performance tweaking. other stuff is more important
